[variables]
    PHP_EXTENSION_MYSQLI = "1"
    PHP_EXTENSION_PDO_MYSQL = "1"

[phases.setup]
    nixPkgs = ["...", "php82", "php82Extensions.mysqli", "php82Extensions.pdo-mysql"]

[phases.build]
    # Keep this only if you have a composer.json file
    cmds = ["composer install --no-dev --optimize-autoloader"]